# -*- coding: utf-8 -*-
"""NTO AI 2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/artemnazemtsev/nto-ai-2026.6ef468ed-0ae1-4d54-b826-a979fa64bafe.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260317/auto/storage/goog4_request%26X-Goog-Date%3D20260317T084144Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D03fb7b71503795cff62445e568ca5059c1b46a915cd8c383cf5f4a5c8d275bac79352649dff69e1e8bad3cd4d4c6a5d702962abeef206c29ce7465320d87fb07e37d3bae5f08367f05da15e2de75fef30196c4fe6a4b1b411290e36ff55c0867e2269d0bf4e073118e13228922397d2c273781eb50de7d80d3f93b928fa4a1c845c624b80e78eda78af93af2fa8b66683376980da1a9fd9c1050ea2a4d08a5b92880c7cb7e9c89c137e427a2719bad621f26a5eabdde2d7fd390a022aa5ec14de779d4a84e90eaa55972a6a20e887060363023b06d92c794dc8cabc1b00111c3d6cc660278477878b2f1dd8e77a9508a22a1f810a9106d80f03f1fbca595ea8c
"""

# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

artemnazemtsev_nto_ai_path = kagglehub.dataset_download('artemnazemtsev/nto-ai')

print('Data source import complete.')

#!pip install implicit

# ============================================================
# CELL 0 — Imports & Config
# ============================================================
import os, gc, warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
from scipy.sparse import csr_matrix
from sklearn.preprocessing import LabelEncoder
from catboost import CatBoostRanker, Pool
import implicit
from tqdm import tqdm

import nltk
nltk.download("stopwords", quiet=True)
from nltk.corpus import stopwords as nltk_sw
from nltk.stem import SnowballStemmer
import re, unicodedata

DATA_DIR    = "/kaggle/input/datasets/artemnazemtsev/nto-ai"
OUTPUT_PATH = "submission.csv"

TOP_K               = 20
CANDIDATES_PER_USER = 150
INCIDENT_DAYS       = 30
HOLDOUT_DAYS        = 30
RANDOM_SEED         = 42

TOP_GENRE_PER_USER  = 10
TOP_AUTHOR_PER_USER = 10
EDS_PER_GENRE       = 40
EDS_PER_AUTHOR      = 30
GLOBAL_POP_CANDS    = 100

ALS_FACTORS = 64
ALS_ITERS   = 30

print("Imports OK")
print(f"Files: {sorted(os.listdir(DATA_DIR))}")

# ============================================================
# CELL 1 — Load Data
# ============================================================
interactions = pd.read_csv(
    f"{DATA_DIR}/interactions.csv",
    parse_dates=["event_ts"],
    dtype={"user_id": np.int64, "edition_id": np.int64, "event_type": np.int8},
)
targets     = pd.read_csv(f"{DATA_DIR}/targets.csv",     dtype={"user_id": np.int64})
editions    = pd.read_csv(f"{DATA_DIR}/editions.csv",    dtype={"edition_id": np.int64, "book_id": np.int64, "author_id": np.int64})
book_genres = pd.read_csv(f"{DATA_DIR}/book_genres.csv", dtype={"book_id": np.int64, "genre_id": np.int64})
users       = pd.read_csv(f"{DATA_DIR}/users.csv",       dtype={"user_id": np.int64})
authors     = pd.read_csv(f"{DATA_DIR}/authors.csv",     dtype={"author_id": np.int64})
genres      = pd.read_csv(f"{DATA_DIR}/genres.csv",      dtype={"genre_id": np.int64})

T_MAX            = interactions["event_ts"].max()
T_INCIDENT_START = T_MAX - pd.Timedelta(days=INCIDENT_DAYS)
T_TRAIN_SPLIT    = T_INCIDENT_START - pd.Timedelta(days=HOLDOUT_DAYS)

print(f"interactions : {len(interactions):,}")
print(f"targets      : {len(targets):,}")
print(f"editions     : {len(editions):,}")
print(f"Data range   : {interactions['event_ts'].min().date()} -> {T_MAX.date()}")
print(f"Incident start : {T_INCIDENT_START.date()}")
print(f"Train split    : {T_TRAIN_SPLIT.date()}")

# ============================================================
# CELL 3 — Feature Engineering Functions
# ============================================================

def build_edition_features(iact: pd.DataFrame, T_incident) -> pd.DataFrame:
    """
    Edition-level features. iact — срез interactions для данного сплита.
    Возвращает DataFrame, индексированный по edition_id.
    """
    pos  = iact[iact["event_type"].isin([1, 2])]

    ep    = pos.groupby("edition_id").size().rename("edition_pop")
    ep_w  = pos[pos["event_type"] == 1].groupby("edition_id").size().rename("wishlist_pop")
    ep_r  = pos[pos["event_type"] == 2].groupby("edition_id").size().rename("read_pop")
    ep_rc = (pos[pos["event_ts"] >= T_incident]
             .groupby("edition_id").size().rename("edition_recent_pop"))
    ep_uu = pos.groupby("edition_id")["user_id"].nunique().rename("edition_unique_users")

    rated = iact[(iact["event_type"] == 2) & iact["rating"].notna()]
    rat   = rated.groupby("edition_id")["rating"].agg(
        rating_mean="mean", rating_std="std", rating_count="count"
    )

    bgc = book_genres.groupby("book_id")["genre_id"].count().rename("book_genre_count")

    feat = editions[[
        "edition_id", "book_id", "author_id",
        "publication_year", "age_restriction", "language_id", "publisher_id",
        "title_clean", "desc_clean",
    ]].copy().set_index("edition_id")

    feat = feat.join(ep).join(ep_w).join(ep_r).join(ep_rc).join(ep_uu).join(rat).join(bgc, on="book_id")

    zero_cols = [
        "edition_pop", "wishlist_pop", "read_pop",
        "edition_recent_pop", "edition_unique_users",
        "rating_mean", "rating_std", "rating_count", "book_genre_count",
    ]
    feat[zero_cols] = feat[zero_cols].fillna(0)

    feat["wishlist_ratio"] = feat["wishlist_pop"] / (feat["edition_pop"] + 1)
    feat["read_ratio"]     = feat["read_pop"]     / (feat["edition_pop"] + 1)
    feat["pop_log"]        = np.log1p(feat["edition_pop"]).astype(np.float32)
    feat["recent_pop_log"] = np.log1p(feat["edition_recent_pop"]).astype(np.float32)

    feat["title_clean"]  = feat["title_clean"].fillna("")
    feat["desc_clean"]   = feat["desc_clean"].fillna("")
    feat["title_len"]    = feat["title_clean"].str.split().str.len().fillna(0).astype(np.float32)
    feat["desc_len"]     = feat["desc_clean"].str.split().str.len().fillna(0).astype(np.float32)
    feat["title_in_desc"]= feat.apply(
        lambda r: float(len(set(r["title_clean"].split()) & set(r["desc_clean"].split()))), axis=1
    ).astype(np.float32)

    f32 = [
        "edition_pop", "wishlist_pop", "read_pop", "edition_recent_pop",
        "edition_unique_users", "rating_mean", "rating_std", "rating_count",
        "book_genre_count", "wishlist_ratio", "read_ratio",
    ]
    feat[f32] = feat[f32].astype(np.float32)
    feat["publication_year"] = feat["publication_year"].fillna(0).astype(np.float32)
    feat["age_restriction"]  = feat["age_restriction"].fillna(0).astype(np.float32)
    feat["language_id"]      = feat["language_id"].fillna(-1).astype(np.int32)
    feat["publisher_id"]     = feat["publisher_id"].fillna(-1).astype(np.int32)
    feat["author_id"]        = feat["author_id"].fillna(-1).astype(np.int64)
    feat["book_id"]          = feat["book_id"].fillna(-1).astype(np.int64)
    return feat


def build_user_features(iact: pd.DataFrame, T_incident) -> pd.DataFrame:
    """User-level features. Возвращает DataFrame, индексированный по user_id."""
    pos = iact[iact["event_type"].isin([1, 2])]

    u_total = pos.groupby("user_id").size().rename("user_activity")
    u_hist  = (pos[pos["event_ts"] <  T_incident].groupby("user_id").size()
               .rename("user_activity_hist"))
    u_inc   = (pos[pos["event_ts"] >= T_incident].groupby("user_id").size()
               .rename("user_activity_inc"))
    u_wish  = (pos[pos["event_type"] == 1].groupby("user_id").size()
               .rename("user_wishlist_count"))
    u_read  = (pos[pos["event_type"] == 2].groupby("user_id").size()
               .rename("user_read_count"))
    u_ue    = pos.groupby("user_id")["edition_id"].nunique().rename("user_uniq_editions")

    rated = iact[(iact["event_type"] == 2) & iact["rating"].notna()]
    u_rat = rated.groupby("user_id")["rating"].agg(
        user_avg_rating="mean", user_rating_count="count"
    )

    feat = users[["user_id", "gender", "age"]].copy().set_index("user_id")
    feat = (feat
            .join(u_total).join(u_hist).join(u_inc)
            .join(u_wish).join(u_read).join(u_ue).join(u_rat))

    zero_cols = [
        "user_activity", "user_activity_hist", "user_activity_inc",
        "user_wishlist_count", "user_read_count", "user_uniq_editions",
        "user_avg_rating", "user_rating_count", "gender", "age",
    ]
    feat[zero_cols] = feat[zero_cols].fillna(0)

    feat["user_wish_ratio"]   = feat["user_wishlist_count"] / (feat["user_activity"] + 1)
    feat["user_read_ratio"]   = feat["user_read_count"]     / (feat["user_activity"] + 1)
    feat["user_activity_log"] = np.log1p(feat["user_activity"])
    feat["user_inc_ratio"]    = feat["user_activity_inc"]   / (feat["user_activity"] + 1)

    return feat.astype(np.float32)


def build_user_genre_profile(iact: pd.DataFrame) -> pd.DataFrame:
    """User × genre affinity. Возвращает плоскую таблицу [user_id, genre_id, user_genre_affinity]."""
    pos = iact[iact["event_type"].isin([1, 2])]
    e2b = editions[["edition_id", "book_id"]].drop_duplicates()
    df  = (pos.merge(e2b, on="edition_id", how="left")
               .merge(book_genres, on="book_id", how="left")
               .dropna(subset=["genre_id"]))
    df["genre_id"] = df["genre_id"].astype(np.int64)

    profile = df.groupby(["user_id", "genre_id"]).size().rename("cnt").reset_index()
    total   = profile.groupby("user_id")["cnt"].transform("sum")
    profile["user_genre_affinity"] = (profile["cnt"] / total).astype(np.float32)
    return profile[["user_id", "genre_id", "user_genre_affinity"]]


def build_user_author_profile(iact: pd.DataFrame) -> pd.DataFrame:
    """User × author affinity. Возвращает плоскую таблицу [user_id, author_id, user_author_affinity]."""
    pos = iact[iact["event_type"].isin([1, 2])]
    e2a = editions[["edition_id", "author_id"]].drop_duplicates()
    df  = pos.merge(e2a, on="edition_id", how="left").dropna(subset=["author_id"])
    df["author_id"] = df["author_id"].astype(np.int64)

    profile = df.groupby(["user_id", "author_id"]).size().rename("cnt").reset_index()
    total   = profile.groupby("user_id")["cnt"].transform("sum")
    profile["user_author_affinity"] = (profile["cnt"] / total).astype(np.float32)
    return profile[["user_id", "author_id", "user_author_affinity"]]


print("Feature functions OK")

# ============================================================
# CELL 2 — Text Preprocessing (OPTIMIZED)
# ============================================================

# 1. Устанавливаем и инициализируем pandarallel для использования всех ядер CPU
!pip install pandarallel -q
from pandarallel import pandarallel
# Инициализация (progress_bar=True показывает прогресс-бар)
pandarallel.initialize(progress_bar=True, nb_workers=os.cpu_count())

# 2. Настраиваем NLTK (глобально, чтобы это было видно всем процессам)
import nltk
nltk.download("stopwords", quiet=True)
from nltk.corpus import stopwords as nltk_sw
from nltk.stem import SnowballStemmer
import re, unicodedata

RU_STOP   = set(nltk_sw.words("russian"))
EN_STOP   = set(nltk_sw.words("english"))
STOPWORDS = RU_STOP | EN_STOP
STEMMER   = SnowballStemmer("russian")

# Регулярные выражения
_RE_HTML  = re.compile(r"<[^>]+>")
_RE_CHARS = re.compile(r"[^а-яёa-z\s]")

# 3. Функция для тяжелой части: стемминг и фильтрация (будет параллелиться)
def stem_and_filter(text: str, max_tokens: int = 120) -> str:
    """
    Получает уже очищенный текст, делает стемминг и отсечку.
    """
    if not isinstance(text, str) or not text.strip():
        return ""
    tokens = [
        STEMMER.stem(t)
        for t in text.split()
        if len(t) >= 3 and t not in STOPWORDS
    ]
    return " ".join(tokens[:max_tokens])

# 4. Функция для легкой части: очистка (выполняется векторизовано, очень быстро)
def vector_clean(series: pd.Series) -> pd.Series:
    """
    Быстрая очистка через встроенные методы Pandas (работают на C).
    """
    s = series.fillna("").astype(str)
    s = s.str.normalize("NFKC")               # Нормализация (ё -> е и т.д.)
    s = s.str.replace(_RE_HTML, " ", regex=True) # Удаление HTML
    s = s.str.lower()                         # Нижний регистр
    s = s.str.replace(_RE_CHARS, " ", regex=True) # Удаление мусорных символов
    return s

# 5. Применяем
# Сначала быстрая векторизованная очистка для всего столбца
print("Cleaning text (Vectorized)...")
t_prep = vector_clean(editions["title"])
d_prep = vector_clean(editions["description"])

# Затем параллельный стемминг (самый долгий этап разбит на все ядра)
print("Stemming titles (Parallel)...")
editions["title_clean"] = t_prep.parallel_apply(stem_and_filter)

print("Stemming descriptions (Parallel)...")
# Для описаний передаем max_tokens=120 через lambda
editions["desc_clean"] = d_prep.parallel_apply(lambda x: stem_and_filter(x, max_tokens=120))

# Средний рейтинг изданий (без изменений)
ed_avg_rating_map = (
    interactions[interactions["event_type"] == 2]
    .groupby("edition_id")["rating"].mean()
    .fillna(0).to_dict()
)

print(f"Пример title_clean : {editions['title_clean'].iloc[5]}")
print(f"Пример desc_clean  : {editions['desc_clean'].iloc[5][:150]}")

# ============================================================
# CELL 4 — ALS Training (WITH TIME DECAY)
# ============================================================
def train_als_with_decay(iact: pd.DataFrame, half_life_days=30):
    pos = iact[iact["event_type"].isin([1, 2])].copy()

    # Базовые веса
    pos["base_w"] = pos["event_type"].map({1: 1.0, 2: 2.0})

    # Считаем Time Decay
    pos['event_ts'] = pd.to_datetime(pos['event_ts'])
    max_date = pos['event_ts'].max()
    pos['days_old'] = (max_date - pos['event_ts']).dt.days.clip(lower=0)

    # Экспоненциальное затухание: через half_life_days вес падает в 2 раза
    pos['decay_weight'] = np.exp(-np.log(2) * pos['days_old'] / half_life_days)
    pos["w"] = (pos["base_w"] * pos['decay_weight']).astype(np.float32)

    ue_enc = LabelEncoder()
    ei_enc = LabelEncoder()
    u_idx  = ue_enc.fit_transform(pos["user_id"])
    e_idx  = ei_enc.fit_transform(pos["edition_id"])

    mat = csr_matrix((pos["w"].values, (u_idx, e_idx)), shape=(len(ue_enc.classes_), len(ei_enc.classes_)))

    als = implicit.als.AlternatingLeastSquares(factors=64, iterations=15, use_gpu=True, random_state=42)
    als.fit(mat)

    U = als.user_factors.to_numpy().astype(np.float32)
    V = als.item_factors.to_numpy().astype(np.float32)

    U_normed = U / np.linalg.norm(U, axis=1, keepdims=True).clip(min=1e-9)
    V_normed = V / np.linalg.norm(V, axis=1, keepdims=True).clip(min=1e-9)

    u2als = {uid: i for i, uid in enumerate(ue_enc.classes_)}
    e2als = {eid: i for i, eid in enumerate(ei_enc.classes_)}

    return U, V, U_normed, V_normed, u2als, e2als, ue_enc.classes_, ei_enc.classes_

U, V, U_normed, V_normed, u2als, e2als, als_user_ids, als_edition_ids = train_als_with_decay(interactions)

# ============================================================
# CELL 5 — ALS Feature Builder (векторизованный)
# ============================================================
ALS_FACTOR_COLS = [f"als_u_{i}" for i in range(ALS_FACTORS)] +  [f"als_v_{i}" for i in range(ALS_FACTORS)]
ALS_SCALAR_COLS = [
    "als_dot", "als_cos",
    "als_nb_mean_sim", "als_nb_max_sim",
    "als_nb_mean_rating", "als_nb_weighted_rating", "als_nb_read_ratio",
]
ALS_FEAT_COLS = ALS_FACTOR_COLS + ALS_SCALAR_COLS


def build_als_features(df_cands: pd.DataFrame, iact: pd.DataFrame) -> pd.DataFrame:
    """
    Для каждой пары (user, edition) в df_cands вычисляет:
      • 64 user-факторов + 64 item-факторов из ALS
      • als_dot  — скалярное произведение u·v
      • als_cos  — косинусное сходство u·v (нормированные)
      • als_nb_*  — агрегаты по топ-10 ближайшим книгам из истории пользователя
                    в ALS item-пространстве

    iact используется для построения истории пользователя (не течёт метка).
    """
    n = len(df_cands)
    df_r = df_cands.reset_index(drop=True)

    # ── Индексы для всех строк ───────────────────────────────────────────────
    u_ser = df_r["user_id"].map(u2als)       # NaN если нет в ALS
    e_ser = df_r["edition_id"].map(e2als)

    valid_u = u_ser.notna().values
    valid_e = e_ser.notna().values
    valid_ue = valid_u & valid_e

    u_idxs = np.where(valid_u, u_ser.fillna(0).astype(int).values, 0)
    e_idxs = np.where(valid_e, e_ser.fillna(0).astype(int).values, 0)

    # ── Факторы (батчевый lookup) ────────────────────────────────────────────
    u_fac = U[u_idxs].copy();  u_fac[~valid_u] = 0.0
    v_fac = V[e_idxs].copy();  v_fac[~valid_e] = 0.0

    # ── Dot / cosine ─────────────────────────────────────────────────────────
    dots = (u_fac * v_fac).sum(axis=1).astype(np.float32)

    un = U_normed[u_idxs].copy(); un[~valid_u] = 0.0
    vn = V_normed[e_idxs].copy(); vn[~valid_e] = 0.0
    coss = (un * vn).sum(axis=1).astype(np.float32)
    coss[~valid_ue] = 0.0

    # ── История пользователя: user_id → массив индексов ALS-items ───────────
    pos_iact = iact[iact["event_type"].isin([1, 2])]
    read_pairs = set(zip(
        pos_iact[pos_iact["event_type"] == 2]["user_id"],
        pos_iact[pos_iact["event_type"] == 2]["edition_id"],
    ))
    user_hist_idx = {}
    for uid, grp in pos_iact.groupby("user_id"):
        idxs = np.array(
            [e2als[eid] for eid in grp["edition_id"] if eid in e2als], dtype=np.int32
        )
        if len(idxs) > 0:
            user_hist_idx[uid] = idxs

    # ── Агрегаты по топ-10 соседям (цикл по пользователям, не по строкам) ───
    nb_mean_sim     = np.zeros(n, np.float32)
    nb_max_sim      = np.zeros(n, np.float32)
    nb_mean_rating  = np.zeros(n, np.float32)
    nb_weighted_rat = np.zeros(n, np.float32)
    nb_read_ratio   = np.zeros(n, np.float32)

    for uid, grp_df in df_r.groupby("user_id"):
        hist = user_hist_idx.get(uid)
        if hist is None or len(hist) == 0:
            continue

        row_idxs  = grp_df.index.values
        cand_eidxs = e_idxs[row_idxs]
        cand_valid = valid_e[row_idxs]

        if not cand_valid.any():
            continue

        # (n_cands, n_hist) косинусное сходство
        sim_mat = V_normed[cand_eidxs] @ V_normed[hist].T  # (n_cands, n_hist)
        sim_mat[~cand_valid] = 0.0

        k10 = min(10, sim_mat.shape[1])
        top_k = np.argpartition(sim_mat, -k10, axis=1)[:, -k10:]  # (n_cands, k10)

        hist_eids = als_edition_ids[hist]  # оригинальные edition_id

        for li, row_i in enumerate(row_idxs):
            if not cand_valid[li]:
                continue
            tidx    = top_k[li]
            tsims   = sim_mat[li, tidx]
            teids   = hist_eids[tidx]
            ratings = np.array([ed_avg_rating_map.get(eid, 0.0) for eid in teids], np.float32)
            reads   = np.array([(uid, eid) in read_pairs for eid in teids], np.float32)
            w       = np.clip(tsims, 0, None) + 1e-9

            nb_mean_sim[row_i]     = tsims.mean()
            nb_max_sim[row_i]      = tsims.max()
            nb_mean_rating[row_i]  = ratings.mean()
            nb_weighted_rat[row_i] = np.average(ratings, weights=w)
            nb_read_ratio[row_i]   = reads.mean()

    # ── Собираем DataFrame ───────────────────────────────────────────────────
    out = {f"als_u_{i}": u_fac[:, i] for i in range(ALS_FACTORS)}
    out.update({f"als_v_{i}": v_fac[:, i] for i in range(ALS_FACTORS)})
    out["als_dot"]               = dots
    out["als_cos"]               = coss
    out["als_nb_mean_sim"]       = nb_mean_sim
    out["als_nb_max_sim"]        = nb_max_sim
    out["als_nb_mean_rating"]    = nb_mean_rating
    out["als_nb_weighted_rating"]= nb_weighted_rat
    out["als_nb_read_ratio"]     = nb_read_ratio

    return pd.DataFrame(out, index=df_cands.index)


print("ALS feature builder OK")
print(f"ALS_FEAT_COLS ({len(ALS_FEAT_COLS)}): {ALS_SCALAR_COLS}")

# ============================================================
# CELL 6 — Candidate Generation (Full Integrated Version)
# ============================================================

def _genre_index(edition_feat: pd.DataFrame) -> dict:
    # Группируем издания по жанрам, сортируя по популярности внутри жанра
    bg = book_genres.merge(
        edition_feat[["book_id", "pop_log"]].reset_index(), on="book_id", how="inner"
    ).sort_values(["genre_id", "pop_log"], ascending=[True, False])
    return (bg.groupby("genre_id")["edition_id"]
              .apply(lambda x: x.head(EDS_PER_GENRE).tolist())
              .to_dict())

def _author_index(edition_feat: pd.DataFrame) -> dict:
    # Группируем издания по авторам, сортируя по популярности
    tmp = edition_feat[["author_id", "pop_log"]].reset_index()
    tmp = tmp.sort_values(["author_id", "pop_log"], ascending=[True, False])
    return (tmp.groupby("author_id")["edition_id"]
               .apply(lambda x: x.head(EDS_PER_AUTHOR).tolist())
               .to_dict())

def generate_candidates(
    user_ids,
    iact: pd.DataFrame,
    edition_feat: pd.DataFrame,
    user_genre_profile: pd.DataFrame,
    user_author_profile: pd.DataFrame,
    als_model, # Объект implicit.als.AlternatingLeastSquares
    u2als,
    e2als,
    als_edition_ids,
    k: int = CANDIDATES_PER_USER,
) -> pd.DataFrame:

    print("Initializing indexes...")
    genre_idx  = _genre_index(edition_feat)
    author_idx = _author_index(edition_feat)

    # Сет уже виденных (позитивных) пар, чтобы не предлагать их снова
    seen = set(zip(
        iact.loc[iact["event_type"].isin([1, 2]), "user_id"],
        iact.loc[iact["event_type"].isin([1, 2]), "edition_id"],
    ))

    # Топ-N глобально популярных книг
    global_top = (edition_feat["pop_log"]
                  .sort_values(ascending=False)
                  .head(GLOBAL_POP_CANDS).index.tolist())

    # Профили интересов юзеров
    ugp = (user_genre_profile
           .sort_values(["user_id", "user_genre_affinity"], ascending=[True, False])
           .groupby("user_id")
           .apply(lambda g: list(g["genre_id"]))
           .to_dict())

    uap = (user_author_profile
           .sort_values(["user_id", "user_author_affinity"], ascending=[True, False])
           .groupby("user_id")
           .apply(lambda g: list(g["author_id"]))
           .to_dict())

    # История для I2I (Item-to-Item): берем последние 5 айтемов
    pos_iact = iact[iact["event_type"].isin([1, 2])].sort_values('event_ts')
    user_history = pos_iact.groupby('user_id')['edition_id'].apply(lambda x: list(x)[-5:]).to_dict()

    # --- ПРЕДРАСЧЕТ ALS U2I (User-to-Item) ---
    # Делаем батчами через матричное умножение для скорости
    u_idxs = np.array([u2als.get(u, -1) for u in user_ids])
    valid_mask = u_idxs != -1
    valid_u_idxs = u_idxs[valid_mask]
    valid_uids   = np.array(user_ids)[valid_mask]

    als_cands_map = {}

    if len(valid_u_idxs) > 0:
        # Извлекаем факторы напрямую из модели (они уже в numpy после нашего фикса в Cell 4)
        U = als_model.user_factors.to_numpy()
        V = als_model.item_factors.to_numpy()
        u_vecs = U[valid_u_idxs]

        batch_size = 500
        als_top_n = 100 # Сколько брать из ALS U2I

        print(f"Calculating ALS U2I for {len(valid_uids)} users...")
        for i in range(0, len(u_vecs), batch_size):
            batch_u = u_vecs[i:i+batch_size]
            batch_uids = valid_uids[i:i+batch_size]

            # Считаем скоры для всех айтемов
            scores = batch_u @ V.T
            # Находим индексы лучших через partition (быстрее полной сортировки)
            ind = np.argpartition(scores, -als_top_n, axis=1)[:, -als_top_n:]

            for row_idx, uid in enumerate(batch_uids):
                row_scores = scores[row_idx, ind[row_idx]]
                sorted_local_idx = np.argsort(-row_scores)
                top_item_indices = ind[row_idx, sorted_local_idx]
                als_cands_map[uid] = [als_edition_ids[idx] for idx in top_item_indices]

    # --- ОСНОВНОЙ ЦИКЛ СБОРА КАНДИДАТОВ ---
    rows = []
    for uid in tqdm(user_ids, desc="Processing users"):
        cands = {} # eid -> [total_score, src_genre, src_author, src_global, src_u2i, src_i2i]

        def add(eid, score_add, src_idx):
            if (uid, eid) in seen:
                return
            if eid not in cands:
                cands[eid] = [0.0, 0, 0, 0, 0, 0]

            cands[eid][0] += score_add
            cands[eid][src_idx] = 1

        # 1. ALS User-to-Item (U2I)
        for rank, eid in enumerate(als_cands_map.get(uid, [])):
            # Используем Reciprocal Rank для нормировки скоров
            add(eid, 4.0 / (rank + 1), 4)

        # 2. ALS Item-to-Item (I2I)
        u_hist = user_history.get(uid, [])
        for hist_eid in u_hist:
            if hist_eid not in e2als: continue

            # Получаем похожие айтемы через встроенный метод implicit
            # Он эффективен на GPU
            ids, sim_scores = als_model.similar_items(e2als[hist_eid], N=15)

            for rank, (idx, sim) in enumerate(zip(ids, sim_scores)):
                eid = als_edition_ids[idx]
                if eid == hist_eid: continue
                # Вес зависит от косинусной похожести и позиции
                add(eid, (3.0 * sim) / (rank + 1), 5)

        # 3. Жанры (на основе профиля пользователя)
        genre_rank = 0
        for gid in ugp.get(uid, [])[:TOP_GENRE_PER_USER]:
            for eid in genre_idx.get(gid, []):
                add(eid, 1.5 / (genre_rank + 1), 1)
                genre_rank += 1

        # 4. Авторы (на основе профиля пользователя)
        author_rank = 0
        for aid in uap.get(uid, [])[:TOP_AUTHOR_PER_USER]:
            for eid in author_idx.get(aid, []):
                add(eid, 1.5 / (author_rank + 1), 2)
                author_rank += 1

        # 5. Глобальный топ (для «холодных» пользователей)
        for rank, eid in enumerate(global_top):
            add(eid, 0.5 / (rank + 1), 3)

        # Сохраняем топ-K кандидатов для этого пользователя
        sorted_cands = sorted(cands.items(), key=lambda x: -x[1][0])[:k]
        for eid, info in sorted_cands:
            rows.append({
                "user_id": uid,
                "edition_id": eid,
                "cand_score": info[0],
                "src_genre": info[1],
                "src_author": info[2],
                "src_global": info[3],
                "src_als_u2i": info[4],
                "src_als_i2i": info[5],
            })

    df = pd.DataFrame(rows)
    # Оптимизация типов данных для экономии памяти
    df["cand_score"] = df["cand_score"].astype(np.float32)
    source_cols = ["src_genre", "src_author", "src_global", "src_als_u2i", "src_als_i2i"]
    df[source_cols] = df[source_cols].astype(np.int8)

    print(f"Total candidates: {len(df):,}")
    return df

print("Full Candidate Generation logic is ready.")

# ============================================================
# CELL 7 — Feature Lists + build_ranking_dataset
# ============================================================

NUMERIC_FEATURES = [
    # candidate
    "cand_score", "src_genre", "src_author", "src_global", "src_als", # <-- Добавили src_als
    # edition counters
    "edition_pop", "wishlist_pop", "read_pop",
    "edition_recent_pop", "edition_unique_users",
    "rating_mean", "rating_std", "rating_count",
    "wishlist_ratio", "read_ratio",
    "pop_log", "recent_pop_log",
    "publication_year", "age_restriction",
    "language_id", "publisher_id",
    "book_genre_count",
    "title_len", "desc_len", "title_in_desc",
    # user counters
    "gender", "age",
    "user_activity", "user_activity_hist", "user_activity_inc",
    "user_wishlist_count", "user_read_count", "user_uniq_editions",
    "user_avg_rating", "user_rating_count",
    "user_wish_ratio", "user_read_ratio",
    "user_activity_log", "user_inc_ratio",
    # cross user×item
    "user_genre_affinity", "user_author_affinity",
    # ALS
] + ALS_FEAT_COLS

TEXT_FEATURES = ["title_clean", "desc_clean"]

ALL_FEATURES = NUMERIC_FEATURES + TEXT_FEATURES

print(f"Numeric features : {len(NUMERIC_FEATURES)}")
print(f"Text features    : {TEXT_FEATURES}")
print(f"Total            : {len(ALL_FEATURES)}")


# ============================================================
# UPDATED CELL — Feature Engineering (Aggregates & BERT)
# ============================================================
def build_ranking_dataset(
    cands_df: pd.DataFrame,
    u_feat: pd.DataFrame,
    ed_feat: pd.DataFrame,
    iact: pd.DataFrame, # Передаем логи для истории
    bert_feat: pd.DataFrame # Передаем BERT фичи
):
    df = cands_df.copy()

    # 1. Базовые фичи (жанры, авторы, счетчики)
    df = df.merge(u_feat, on="user_id", how="left")
    df = df.merge(ed_feat, on="edition_id", how="left")
    df = df.merge(bert_feat, on="edition_id", how="left") # Добавляем BERT

    # 2. Агрегаты по истории (ALS Neighbors Center of Mass)
    print("Считаем ALS косинусные дистанции до истории юзера...")

    # Берем последние 5 позитивных взаимодействий каждого юзера
    pos_iact = iact[iact["event_type"].isin([1, 2])].sort_values('event_ts')
    recent_history = pos_iact.groupby('user_id').tail(5).groupby('user_id')['edition_id'].apply(list).to_dict()

    als_distances = []

    for row in tqdm(df.itertuples(), total=len(df)):
        uid = row.user_id
        cand_eid = row.edition_id

        hist_eids = recent_history.get(uid, [])
        if not hist_eids or cand_eid not in e2als:
            als_distances.append(0.0)
            continue

        cand_idx = e2als[cand_eid]
        cand_vec = V_normed[cand_idx]

        # Получаем векторы истории
        hist_idxs = [e2als[e] for e in hist_eids if e in e2als]
        if not hist_idxs:
            als_distances.append(0.0)
            continue

        hist_vecs = V_normed[hist_idxs]

        # Центр масс истории (средний вектор)
        center_of_mass = hist_vecs.mean(axis=0)
        center_of_mass /= (np.linalg.norm(center_of_mass) + 1e-9)

        # Скалярное произведение (косинус)
        sim = np.dot(cand_vec, center_of_mass)
        als_distances.append(sim)

    df['als_history_similarity'] = als_distances

    # Добавляем фичу прямого dot product между User и Item в ALS
    df['als_dot_product'] = df.apply(
        lambda x: np.dot(U[u2als[x.user_id]], V[e2als[x.edition_id]])
        if x.user_id in u2als and x.edition_id in e2als else 0.0,
        axis=1
    )

    return df

print("build_ranking_dataset OK")

# ============================================================
# CELL 8 — CatBoost: train & predict
# ============================================================

def _has_gpu() -> bool:
    try:
        import subprocess
        return subprocess.run(["nvidia-smi"], capture_output=True, timeout=5).returncode == 0
    except Exception:
        return False


def train_catboost(rdf: pd.DataFrame, labels: np.ndarray) -> CatBoostRanker:
    """
    Обучает CatBoostRanker (YetiRank).
    Группы без позитивов или без негативов отфильтровываются.
    """
    df = rdf.copy()
    df["label"] = labels.astype(np.float32)

    gpos  = df.groupby("user_id")["label"].sum()
    gcnt  = df.groupby("user_id")["label"].count()
    valid = gpos[(gpos >= 1) & (gpos < gcnt)].index
    df    = df[df["user_id"].isin(valid)].sort_values("user_id").reset_index(drop=True)

    print(f"  Training groups : {df['user_id'].nunique():,}")
    print(f"  Positives       : {int(df['label'].sum()):,} / {len(df):,}")

    feat_cols  = [c for c in NUMERIC_FEATURES if c in df.columns]
    text_cols  = [c for c in TEXT_FEATURES    if c in df.columns]

    pool = Pool(
        data=df[feat_cols + text_cols],
        label=df["label"].values,
        group_id=df["user_id"].values,
        text_features=text_cols,
        feature_names=feat_cols + text_cols,
    )

    use_gpu = _has_gpu()
    model = CatBoostRanker(
        loss_function="YetiRank",
        iterations=600,
        learning_rate=0.07,
        depth=6,
        l2_leaf_reg=3,
        random_seed=RANDOM_SEED,
        verbose=100,
        task_type="GPU" if use_gpu else "CPU",
        text_processing={
            "tokenizers": [
                {"tokenizer_id": "Space", "delimiter": " ", "lowercasing": "true"}
            ],
            "dictionaries": [
                {"dictionary_id": "Word",   "max_dictionary_size": "50000", "gram_order": "1"},
                {"dictionary_id": "BiGram", "max_dictionary_size": "50000", "gram_order": "2"},
            ],
            "feature_processing": {
                "default": [
                    {"dictionaries_names": ["Word"],
                     "feature_calcers": ["BoW"],
                     "tokenizers_names": ["Space"]},
                    {"dictionaries_names": ["BiGram"],
                     "feature_calcers": ["BoW"],
                     "tokenizers_names": ["Space"]},
                ]
            },
        },
    )
    model.fit(pool)
    return model


def predict_and_rank(rdf: pd.DataFrame, model: CatBoostRanker, k: int = TOP_K) -> pd.DataFrame:
    """Скоринг + ранжирование, возвращает [user_id, edition_id, rank]."""
    feat_cols = [c for c in NUMERIC_FEATURES if c in rdf.columns]
    text_cols = [c for c in TEXT_FEATURES    if c in rdf.columns]

    pool   = Pool(data=rdf[feat_cols + text_cols], text_features=text_cols,
                  feature_names=feat_cols + text_cols)
    scores = model.predict(pool)

    out = rdf[["user_id", "edition_id"]].copy()
    out["pred"] = scores
    out = (out.sort_values(["user_id", "pred"], ascending=[True, False])
              .groupby("user_id").head(k).copy())
    out["rank"] = (out.groupby("user_id")["pred"]
                      .rank(method="first", ascending=False).astype(int))
    return out[["user_id", "edition_id", "rank"]]


print("CatBoost functions OK")

# ============================================================
# CELL 9 — Submission Helpers
# ============================================================

def fill_missing(top_k: pd.DataFrame, target_users, edition_feat: pd.DataFrame,
                 k: int = TOP_K) -> pd.DataFrame:
    """Добивает пользователей с < k рекомендациями глобально популярными изданиями."""
    global_top = (edition_feat["pop_log"]
                  .sort_values(ascending=False)
                  .head(k * 3).index.tolist())
    per_user = {u: g for u, g in top_k.groupby("user_id")}
    rows = []

    for uid in target_users:
        grp = per_user.get(uid)
        seen = grp["edition_id"].tolist() if grp is not None else []
        if grp is not None:
            rows.append(grp.head(k))
        need = k - len(seen)
        if need <= 0:
            continue
        extra = [e for e in global_top if e not in set(seen)][:need]
        start = len(seen) + 1
        rows.append(pd.DataFrame({
            "user_id":    uid,
            "edition_id": extra,
            "rank":       range(start, start + len(extra)),
        }))

    return pd.concat(rows, ignore_index=True)


def validate_and_save(sub: pd.DataFrame, output_path: str, k: int = TOP_K) -> pd.DataFrame:
    """Проверяет формат сабмита и сохраняет CSV."""
    errors = []
    tset   = set(targets["user_id"].tolist())

    miss = tset - set(sub["user_id"].unique())
    if miss:
        errors.append(f"{len(miss)} users missing")

    bad_cnt = (sub.groupby("user_id").size() != k).sum()
    if bad_cnt:
        errors.append(f"{bad_cnt} users don't have exactly {k} recs")

    dup_e = (sub.groupby("user_id")["edition_id"].nunique() != k).sum()
    if dup_e:
        errors.append(f"{dup_e} users have duplicate edition_id")

    dup_r = (sub.groupby("user_id")["rank"].nunique() != k).sum()
    if dup_r:
        errors.append(f"{dup_r} users have duplicate rank")

    if errors:
        for e in errors:
            print(f"  ERROR: {e}")
        raise ValueError("Submission invalid")

    sub = sub[["user_id", "edition_id", "rank"]].sort_values(["user_id", "rank"]).reset_index(drop=True)
    sub.to_csv(output_path, index=False)
    print(f"Saved {output_path}  ({len(sub):,} rows)")
    return sub


print("Submission helpers OK")

# ============================================================
# CELL 10 — Temporal split: build training data
# ============================================================
print("=" * 60)
print("STEP 1 | Temporal split")
print("=" * 60)

fake_history = interactions[interactions["event_ts"] < T_TRAIN_SPLIT].copy()
fake_holdout = interactions[
    (interactions["event_ts"] >= T_TRAIN_SPLIT) &
    (interactions["event_ts"] <  T_INCIDENT_START) &
    (interactions["event_type"].isin([1, 2]))
].copy()

print(f"fake_history : {len(fake_history):,} events")
print(f"fake_holdout : {len(fake_holdout):,} positive events")

hist_pos_users  = set(fake_history.loc[fake_history["event_type"].isin([1, 2]), "user_id"])
hold_users      = set(fake_holdout["user_id"])
train_users     = list(hist_pos_users & hold_users)
pos_holdout_pairs = set(zip(fake_holdout["user_id"], fake_holdout["edition_id"]))
print(f"Train users : {len(train_users):,}")

print("\nSTEP 2 | Features (fake_history)")
ed_feat_tr  = build_edition_features(fake_history, T_TRAIN_SPLIT)
u_feat_tr   = build_user_features(fake_history, T_TRAIN_SPLIT)
ugp_tr      = build_user_genre_profile(fake_history)
uap_tr      = build_user_author_profile(fake_history)
print(f"edition_feat: {len(ed_feat_tr):,}  user_feat: {len(u_feat_tr):,}")

print("\nSTEP 3 | Candidates (fake_history)")
train_cands = generate_candidates(
    train_users, fake_history, ed_feat_tr, ugp_tr, uap_tr,
    U, V, u2als, e2als, als_edition_ids # <--- Новые аргументы
)

print("\nSTEP 4 | Ranking dataset + labels")
train_rdf = build_ranking_dataset(train_cands, u_feat_tr, ed_feat_tr, ugp_tr, uap_tr, fake_history)

train_labels = np.array(
    [1 if (u, e) in pos_holdout_pairs else 0
     for u, e in zip(train_rdf["user_id"], train_rdf["edition_id"])],
    dtype=np.float32,
)
print(f"train_rdf : {len(train_rdf):,} rows   positives: {int(train_labels.sum()):,} ({train_labels.mean():.4f})")

# ============================================================
# CELL 11 — Train CatBoostRanker
# ============================================================
print("=" * 60)
print("STEP 5 | Train CatBoostRanker")
print("=" * 60)

model = train_catboost(train_rdf, train_labels)

imp = pd.Series(
    model.get_feature_importance(type="PredictionValuesChange"),
    index=model.feature_names_,
).sort_values(ascending=False)
print("\nTop-20 feature importances:")
print(imp.head(20).to_string())

# ============================================================
# CELL 12 — Full features + test candidates + inference
# ============================================================
print("=" * 60)
print("STEP 6 | Features (full 180 days)")
print("=" * 60)

ed_feat_full = build_edition_features(interactions, T_INCIDENT_START)
u_feat_full  = build_user_features(interactions, T_INCIDENT_START)
ugp_full     = build_user_genre_profile(interactions)
uap_full     = build_user_author_profile(interactions)
print(f"edition_feat: {len(ed_feat_full):,}  user_feat: {len(u_feat_full):,}")

print("\nSTEP 7 | Test candidates")
test_users = targets["user_id"].tolist()
test_cands = generate_candidates(
    test_users, interactions, ed_feat_full, ugp_full, uap_full,
    U, V, u2als, e2als, als_edition_ids # <--- Новые аргументы
)

print("\nSTEP 8 | Test ranking dataset")
test_rdf = build_ranking_dataset(test_cands, u_feat_full, ed_feat_full, ugp_full, uap_full, interactions)
print(f"test_rdf : {len(test_rdf):,} rows")

print("\nSTEP 9 | Predict & rank")
top_k = predict_and_rank(test_rdf, model)
print(f"top_k rows    : {len(top_k):,}")
print(f"users covered : {top_k['user_id'].nunique():,} / {len(test_users):,}")

# ============================================================
# CELL 13 — Fill gaps, validate, save
# ============================================================
print("=" * 60)
print("STEP 10 | Fill + validate + save")
print("=" * 60)

submission = fill_missing(top_k, test_users, ed_feat_full)
submission = validate_and_save(submission, OUTPUT_PATH)

print("\nSample (first 40 rows):")
print(submission.head(40).to_string(index=False))